Build(Login): Construcción vista Login
Global-S1/proptrading-impulse-training-angular pull request #3
Opened 2023-11-07 15:38 UTC by programadordelfuturo21

Se desarrolló la vista de Login, vista inicial de la aplicación App-trader en Angular
Usando Bootstrap y la hoja de estilos globales `styles.scss` en el proceso

2023-11-10 04:18 UTC, danielboggianosa requested changes

2023-11-10 04:18 UTC, danielboggianosa commented on src/app/modules/auth/login/login.component.html
> +<button class="bg-primary w-50">INICIAR SESIÓN</button>
los textos deben ir en archivos separados

2023-11-10 04:18 UTC, danielboggianosa commented on src/app/modules/auth/login/login.component.spec.ts
> +  });
agregar testing

2023-11-17 01:01 UTC, danielboggianosa commented
Resolver conflictos

2023-11-19 23:19 UTC, programadordelfuturo21 commented on src/app/modules/auth/login/login.component.html
> +<button class="bg-primary w-50">INICIAR SESIÓN</button>
Ya se encuentra separado en constantes

2023-11-20 13:45 UTC, programadordelfuturo21 commented on src/app/modules/auth/login/login.component.spec.ts
> +  });
Ya se encuentra realizado el testing

2023-11-20 14:20 UTC, danielboggianosa requested changes

2023-11-20 14:20 UTC, danielboggianosa commented on src/app/shared/core/input/input.component.scss
> +input {
crear clase en lugar de estilizar componentes de html directamente

2023-11-20 14:20 UTC, danielboggianosa commented on src/app/shared/core/input/input.component.spec.ts
> +    expect(component).toBeTruthy();
agregar testing

2023-11-20 14:20 UTC, danielboggianosa commented on src/app/shared/core/theme.styles.interface.ts
> +  // raised: string
eliminar código comentado, o comentar por qué es necesario tenerlo

2023-11-20 14:20 UTC, danielboggianosa commented on src/app/shared/core/theme.styles.ts
> +  // raised: 'mat-focus-indicator btn-block mat-raised-button mat-button-base',
eliminar código comentado

2023-11-20 14:20 UTC, danielboggianosa commented on src/styles.scss
> +app-button {
es mejor usar clases

2023-11-20 15:29 UTC, Programadordelfuturo commented on src/app/shared/core/input/input.component.spec.ts
> +    expect(component).toBeTruthy();
esto ya estaba trabajado en la rama shared, de lo cual se jalaron los cambios de ahí

2023-11-20 15:29 UTC, Programadordelfuturo commented on src/app/shared/core/button/button.component.spec.ts
> +    expect(component).toBeTruthy();
esto ya estaba trabajado en la rama shared, de lo cual se jalaron los cambios de ahí

2023-11-20 15:35 UTC, Programadordelfuturo commented on src/app/modules/auth/login/login.component.ts
> +  constants: ICONSTANTS_LOGIN = constantsLogin
Se esta cambiando "contants" por "loginConstants"

2023-11-20 15:41 UTC, Programadordelfuturo commented on src/app/modules/auth/footer/footer.component.ts
> +  constants: ICONSTANTS_FOOTER = CONSTANTS_FOOTER
Se esta cambiando "contants" por "footerConstants"

2023-11-20 15:41 UTC, Programadordelfuturo commented on src/app/modules/auth/auth.component.ts
> +  constants: ICONSTANTS_AUTH = CONSTANTS_AUTH
Se esta cambiando "contants" por "authConstants"

2023-11-20 15:58 UTC, Programadordelfuturo commented on src/app/modules/auth/login/login.component.spec.ts
> +    const registerLink = fixture.debugElement.query(By.css('span a')).nativeElement;
cambiado y revisado

![image](https://github.com/Global-S1/proptrading-impulse-training-angular/assets/108241186/0eb80132-fc29-4acb-ae3a-f249b39cfade)
![image](https://github.com/Global-S1/proptrading-impulse-training-angular/assets/108241186/ef367c09-2bba-4333-9213-422023f54480)

2023-11-20 16:00 UTC, Programadordelfuturo commented on src/app/modules/auth/login/login.component.spec.ts
> +    const socialIcons = fixture.debugElement.queryAll(By.css('div img'));
cambiado y revisado

![image](https://github.com/Global-S1/proptrading-impulse-training-angular/assets/108241186/ef367c09-2bba-4333-9213-422023f54480)

2023-11-20 18:03 UTC, Programadordelfuturo commented on src/app/modules/auth/login/utils/constants.ts
> +export const constantsLogin: ICONSTANTS_LOGIN = {
Estoy agregando constantsLogin ya que en el nombre quiero que se distinga lo más rápido posible, Aunque este nombre queria que cambiarlo por letras mayusculas "CONSTANST_LOGIN" y de lo cual las otras constantes estan con el mismo formato de nombre (letras mayusculas con snake case), pero entonces si cambio aquí "constantsLogin" por "pageContent" tendria que cambiarlos en los demás nombres de las constantes
¿No lo haría muy generico, ya que la diferencia que tienen los archivos "constants" solamente es el nombre de su contante ?

2023-11-20 18:04 UTC, Programadordelfuturo commented on src/app/modules/auth/login/utils/constants.interface.ts
> +interface IFormInput {
Listo

2023-11-20 18:04 UTC, Programadordelfuturo commented on src/app/modules/auth/login/login.component.spec.ts
> +  it('should display "Don\'t have an account? Register" link', () => {
Listo

2023-11-20 18:05 UTC, Programadordelfuturo commented on src/app/modules/auth/login/components/social-login/social-login.component.spec.ts
> +  });
Listo

2023-11-20 18:08 UTC, Programadordelfuturo commented on src/app/shared/core/theme.styles.interface.ts
> +  // raised: string
Eliminado

2023-11-20 18:08 UTC, Programadordelfuturo commented on src/app/shared/core/theme.styles.ts
> +  // raised: 'mat-focus-indicator btn-block mat-raised-button mat-button-base',
eliminado

2023-11-20 18:21 UTC, Programadordelfuturo commented on src/styles.scss
> +app-button {
si es un estilo global y lo estoy mandando a scss/base

2023-11-20 18:21 UTC, Programadordelfuturo commented on src/app/shared/core/input/input.component.scss
> +input {
como en la observación anterior, si es un estilo global y lo estoy mandando a scss/base

2023-11-20 18:21 UTC, Programadordelfuturo commented on src/app/shared/core/button/button.component.scss
> +button {
si es un estilo global y lo estoy mandando a scss/base

2023-11-20 18:29 UTC, Programadordelfuturo commented on src/app/shared/core/input/input.component.spec.ts
> +    expect(component).toBeTruthy();
Listo

2023-11-20 18:29 UTC, Programadordelfuturo commented on src/app/shared/core/theme.styles.interface.ts
> +  // raised: string
Listo

2023-11-20 18:30 UTC, Programadordelfuturo commented on src/app/shared/core/theme.styles.ts
> +  // raised: 'mat-focus-indicator btn-block mat-raised-button mat-button-base',
Listo

2023-11-20 23:04 UTC, danielboggianosa requested changes

2023-11-20 23:04 UTC, danielboggianosa commented on src/app/shared/core/button/button.component.spec.ts
> +  it('test at dinamic text ', () => {
Lineamiento para todos los tests:
Tienes que establecer una condicion y poner la descripción de lo que se espera.

2023-11-20 23:04 UTC, danielboggianosa commented on src/app/shared/core/input/input.component.spec.ts
> +    expect(component).toBeTruthy();
lo mismo que te dije en el comentario anterior

2023-11-20 23:04 UTC, danielboggianosa commented on src/styles.scss
> +  app-login {
Es mejor usar clases en lugar de hacer los estilos directamente al selector del componente

2023-11-20 23:07 UTC, danielboggianosa commented on src/app/modules/auth/auth.component.ts
> +  constants: ICONSTANTS_AUTH = CONSTANTS_AUTH
Si bien se está especificando que son constantes de Auth. La palabra constants debería evitarse ya que se puede ser más específico respecto a lo que hace esa constante, o qué información contiene.
Recuerda que el propósito de que todos estos textos estén en archivos separados, es que puedan ser tomadas de un servicio.

2023-11-20 23:08 UTC, danielboggianosa commented on src/app/modules/auth/footer/footer.component.ts
> +  constants: ICONSTANTS_FOOTER = CONSTANTS_FOOTER
Al final me estás diciendo lo mismo. Solo estás agregando el nombre del componente a una propidad del mismo componente. Pero no me habla del contenido.

2023-11-20 23:09 UTC, danielboggianosa commented on src/app/modules/auth/login/login.component.spec.ts
> +    const registerLink = fixture.debugElement.query(By.css('span a')).nativeElement;
Usa este mismo lineamiento para todos los testing

2023-11-20 23:21 UTC, danielboggianosa requested changes

2023-11-20 23:21 UTC, danielboggianosa commented on src/app/modules/auth/login/login.component.spec.ts
> +  it('should display "Don\'t have an account? Register" link', () => {
No veo el "WHEN"

2023-11-21 16:57 UTC, programadordelfuturo21 commented on src/app/modules/auth/auth.component.ts
> +  constants: ICONSTANTS_AUTH = CONSTANTS_AUTH
Okey ya cambie el nombre de "contants" por "pageContent" y la importación del contenido de la página la llamaré "pageContentAuth", con los siguientes PR incluiré la misma nomenclatura

2023-11-21 17:03 UTC, programadordelfuturo21 commented on src/app/modules/auth/login/login.component.ts
> +  constants: ICONSTANTS_LOGIN = constantsLogin
Modificado:

pageContent: IPAGE_CONTENT_LOGIN = PAGE_CONTENT_LOGIN

2023-11-21 17:06 UTC, programadordelfuturo21 commented on src/app/modules/auth/login/utils/constants.ts
> +export const constantsLogin: ICONSTANTS_LOGIN = {
Listo

2023-11-21 17:49 UTC, programadordelfuturo21 commented on src/app/modules/auth/auth.component.spec.ts
> +  it('That the logo is the right one', () => {
Listo

2023-11-21 18:02 UTC, programadordelfuturo21 commented
En el último commit que realicé a esta rama se resolvieron las observaciones que hizó Daniel, como lo son cambios de nombres a las contantes, cambios de descripción en las pruebas unitarias, siguiendo este formato "should display X, when Y happens",

2023-11-27 16:56 UTC, danielboggianosa approved these changes

2023-11-27 16:56 UTC, merged